//! Custom widgets for Toad TUI
//!
//! Reusable UI components following Ratatui patterns

pub mod accept_reject_panel;
pub mod ai_diff_view;
pub mod card_preview;
pub mod charts;
pub mod chat_panel;
pub mod collapsible;
pub mod conflict_resolver;
pub mod contextual_help;
pub mod core;
pub mod demo_mode;
pub mod event_metrics;
pub mod file_preview_manager;
pub mod filetree;
pub mod fps;
pub mod git;
pub mod input;
pub mod layout;
pub mod memory;
pub mod mode_indicator;
pub mod notifications;
pub mod progress;
pub mod render_profiler;
pub mod selection;
pub mod session_manager;
pub mod suggestions_widget;
pub mod undo_redo;
pub mod vim_macros;
pub mod workspace;

pub use accept_reject_panel::{AcceptRejectPanel, ChangeState, ProposedChange};
pub use ai_diff_view::{AIDiffView, AIDiffLine, AIDiffLineType, DiffHunk, DiffViewMode};
pub use card_preview::{CardPreview, CardPriority, PreviewPosition};
pub use charts::*;
pub use chat_panel::{ChatMessage, ChatPanel, MessageRole};
pub use collapsible::{CollapsibleList, CollapsibleSection};
pub use conflict_resolver::{ConflictRegion, ConflictResolution, ConflictResolver, ConflictViewMode};
pub use context_menu::{ContextMenu, MenuItem};
pub use contextual_help::{ContextualHelp, HelpContext, HelpEntry};
pub use core::*;
pub use demo_mode::{DemoMode, DemoState, DemoStep};
pub use event_metrics::EventMetrics;
pub use file_preview_manager::{FilePreviewManager, PreviewState};
pub use filetree::{FileTree, FileTreeNode, FileTreeNodeType};
pub use floating::{FloatingWindow, FloatingWindowManager, WindowPosition};
pub use fps::FpsCounter;
pub use git::*;
pub use input::*;
pub use layout::*;
pub use memory::{MemoryMonitor, MemoryStats};
pub use mode_indicator::{EditorMode, IndicatorStyle, ModeIndicator};
pub use notifications::*;
pub use progress::*;
pub use render_profiler::{ComponentStats, RenderProfiler};
pub use selection::*;
pub use session_manager::{SessionData, SessionManager};
pub use suggestions_widget::{RelevanceScore, SmartSuggestions, Suggestion};
pub use undo_redo::{Action, UndoRedoManager};
pub use vim_macros::{MacroAction, MacroRecorder, MarkRegistry};
pub use workspace::{Workspace, WorkspaceManager};
