//! Custom widgets for Toad TUI
//!
//! Reusable UI components following Ratatui patterns

pub mod animation;
pub mod bar_chart;
pub mod borders;
pub mod breadcrumbs;
pub mod canvas;
pub mod chart;
pub mod chat_panel;
pub mod collapsible;
pub mod command_mode;
pub mod context_menu;
pub mod dialog;
pub mod event_metrics;
pub mod file_preview_manager;
pub mod filetree;
pub mod floating;
pub mod fps;
pub mod git_branch_manager;
pub mod git_commit_dialog;
pub mod git_diff_viewer;
pub mod git_graph;
pub mod git_stage_ui;
pub mod git_status_panel;
pub mod help;
pub mod icons;
pub mod input;
pub mod input_dialog;
pub mod input_prompt;
pub mod line_chart;
pub mod live_graph;
pub mod memory;
pub mod minimap;
pub mod modal;
pub mod mode_indicator;
pub mod model_selector;
pub mod multiselect;
pub mod palette;
pub mod panel;
pub mod preview;
pub mod progress;
pub mod quick_actions;
pub mod render_profiler;
pub mod scatter_plot;
pub mod scrollbar;
pub mod session_manager;
pub mod smart_suggestions;
pub mod sparkline;
pub mod spinner;
pub mod split;
pub mod statusline;
pub mod tabbar;
pub mod table;
pub mod textarea;
pub mod toast;
pub mod token_counter;
pub mod undo_redo;
pub mod vim_macros;
pub mod vim_mode;
pub mod welcome;
pub mod workspace;

pub use animation::{Animation, AnimationState, EasingFunction};
pub use bar_chart::{BarChart as BarChartWidget, BarData, BarDirection};
pub use borders::{BorderSet, BorderStyle};
pub use breadcrumbs::{BreadcrumbSegment, Breadcrumbs};
pub use canvas::{Canvas, Shape};
pub use chart::{BarChart, BarOrientation, LineChart, LineStyle, ScatterPlot};
pub use chat_panel::{ChatMessage, ChatPanel, MessageRole};
pub use collapsible::{CollapsibleList, CollapsibleSection};
pub use command_mode::CommandMode;
pub use context_menu::{ContextMenu, MenuItem};
pub use dialog::{ConfirmDialog, DialogOption};
pub use event_metrics::EventMetrics;
pub use file_preview_manager::{FilePreviewManager, PreviewState};
pub use filetree::{FileTree, FileTreeNode, FileTreeNodeType};
pub use floating::{FloatingWindow, FloatingWindowManager, WindowPosition};
pub use fps::FpsCounter;
pub use git_branch_manager::{BranchMode, GitBranchManager};
pub use git_commit_dialog::{CommitDialogState, GitCommitDialog};
pub use git_diff_viewer::{DiffLine, DiffLineType, GitDiffViewer};
pub use git_graph::{GitCommit, GitGraph};
pub use git_stage_ui::{FileChangeType, GitStageUI, StageFileEntry, StagePane};
pub use git_status_panel::{FileStatus, GitFile, GitStatusPanel};
pub use help::HelpScreen;
pub use icons::{FileType, GitStatus, Icons, StatusIcon};
pub use input::InputField;
pub use input_dialog::{InputDialog, InputDialogState};
pub use input_prompt::InputPrompt;
pub use line_chart::{DataSeries, LineChart as LineChartWidget};
pub use live_graph::{GraphType, LiveGraph};
pub use memory::{MemoryMonitor, MemoryStats};
pub use minimap::{Minimap, MinimapMode};
pub use modal::{Modal, ModalType};
pub use mode_indicator::{EditorMode, IndicatorStyle, ModeIndicator};
pub use model_selector::{ModelInfo, ModelSelector};
pub use multiselect::MultiSelect;
pub use palette::{CommandPalette, PaletteCommand};
pub use panel::Panel;
pub use preview::PreviewPane;
pub use progress::{MultiStageProgress, ProgressBar, StageStatus};
pub use quick_actions::{QuickAction, QuickActions};
pub use render_profiler::{ComponentStats, RenderProfiler};
pub use scatter_plot::{ScatterPlot as ScatterPlotWidget, ScatterSeries};
pub use scrollbar::{Scrollbar, ScrollbarOrientation, ScrollbarState};
pub use session_manager::{SessionData, SessionManager};
pub use smart_suggestions::{RelevanceScore, SmartSuggestions, Suggestion};
pub use sparkline::{Sparkline, SparklineStyle};
pub use spinner::{Spinner, SpinnerStyle};
pub use split::{PaneBorderStyle, SplitDirection, SplitPane, SplitPaneError, SplitSize};
pub use statusline::{SectionAlignment, StatusLevel, StatusSection, Statusline};
pub use tabbar::TabBar;
pub use table::{ColumnAlignment, DataTable, TableColumn};
pub use textarea::Textarea;
pub use toast::{Toast, ToastLevel, ToastManager};
pub use token_counter::{CostModel, TokenCounter, TokenUsage};
pub use undo_redo::{Action, UndoRedoManager};
pub use vim_macros::{MacroAction, MacroRecorder, MarkRegistry};
pub use vim_mode::{EditMode, Selection, VimMode};
pub use welcome::WelcomeScreen;
pub use workspace::{Workspace, WorkspaceManager};
