//! Custom widgets for Toad TUI
//!
//! Reusable UI components following Ratatui patterns

pub mod animation;
pub mod bar_chart;
pub mod borders;
pub mod canvas;
pub mod dialog;
pub mod event_metrics;
pub mod filetree;
pub mod fps;
pub mod git_graph;
pub mod help;
pub mod icons;
pub mod input;
pub mod input_dialog;
pub mod input_prompt;
pub mod line_chart;
pub mod live_graph;
pub mod memory;
pub mod modal;
pub mod palette;
pub mod progress;
pub mod render_profiler;
pub mod scatter_plot;
pub mod sparkline;
pub mod spinner;
pub mod split;
pub mod table;
pub mod textarea;
pub mod toast;
pub mod vim_macros;
pub mod vim_mode;
pub mod welcome;

pub use animation::{Animation, AnimationState, EasingFunction};
pub use bar_chart::{BarChart, BarData, BarDirection};
pub use borders::{BorderSet, BorderStyle};
pub use canvas::{Canvas, Shape};
pub use dialog::{ConfirmDialog, DialogOption};
pub use event_metrics::EventMetrics;
pub use filetree::{FileTree, FileTreeNode, FileTreeNodeType};
pub use fps::FpsCounter;
pub use git_graph::{GitCommit, GitGraph};
pub use help::HelpScreen;
pub use icons::{FileType, GitStatus, Icons, StatusIcon};
pub use input::InputField;
pub use line_chart::{DataSeries, LineChart};
pub use live_graph::{GraphType, LiveGraph};
pub use memory::{MemoryMonitor, MemoryStats};
pub use input_dialog::{InputDialog, InputDialogState};
pub use input_prompt::InputPrompt;
pub use modal::{Modal, ModalType};
pub use palette::{CommandPalette, PaletteCommand};
pub use progress::{MultiStageProgress, ProgressBar, StageStatus};
pub use render_profiler::{ComponentStats, RenderProfiler};
pub use scatter_plot::{ScatterPlot, ScatterSeries};
pub use sparkline::{Sparkline, SparklineStyle};
pub use spinner::{Spinner, SpinnerStyle};
pub use split::{PaneBorderStyle, SplitDirection, SplitPane, SplitPaneError, SplitSize};
pub use table::{ColumnAlignment, DataTable, TableColumn};
pub use textarea::Textarea;
pub use toast::{Toast, ToastLevel, ToastManager};
pub use vim_macros::{MacroAction, MacroRecorder, MarkRegistry};
pub use vim_mode::{EditMode, ModeIndicator, Selection, VimMode};
pub use welcome::WelcomeScreen;
